name: Deploy Hugo website
on:
  push:
    branches:
      - master
    
jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: archlinux:latest

    steps:
    - name: Prepare the build environment
      run: pacman -Syu tree git --noconfirm

    # Breaking change: since Hugo 0.73.0 there is a breaking change that requires
    # a site update. As a workaround, we downgrade Hugo to an earlier version.
    # For more details check https://gohugo.io/news/0.73.0-relnotes/
    - name: Use Hugo 0.72.0
      run: pacman -U https://archive.archlinux.org/packages/h/hugo/hugo-0.72.0-1-x86_64.pkg.tar.zst --noconfirm

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'

    # Uses the build.sh script to create `api/v?/` endpoint
    - name: Build the website
      run: ./build.sh

    - name: Archive Production Artifact
      uses: actions/upload-artifact@master
      with:
        name: prod
        path: public
  
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: prod
          path: public

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
